name: Deploy to Tracker Worker

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "tracker/**" # Trigger deployment for Tracker when files in 'tracker' folder change

jobs:
  deploy-tracker:
    runs-on: ubuntu-latest
    name: Deploy Tracker
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: "latest"

      - name: Install wrangler
        run: npm install -g wrangler

      - name: Set up Cloudflare credentials
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          echo "CLOUDFLARE_API_TOKEN=$CLOUDFLARE_API_TOKEN" >> $GITHUB_ENV

      - name: Deploy Tracker
        run: |
          cd tracker
          DOMAIN=${{ secrets.CF_DOMAIN }} \
          WORKER_NAME=${{ secrets.CF_TRACKER_WORKER }} \
          KV_NAME=${{ secrets.CF_KV_NAME }} \
          KV_NAMESPACE_ID=${{ secrets.CF_KV_NAMESPACE_ID }} \
          RATE_KV_NAME=${{ secrets.RATE_KV_NAME }} \
          RATE_NAMESPACE_ID=${{ secrets.RATE_NAMESPACE_ID }} \
          bash deploy.sh
